### ISSUE TITLE
Update Wiki contents after project rewrite

### ISSUE THREAD

**Issue by leonhard-s** [leonhard-s/auraxium#20]
The Wiki is still refering to the original, pre-rewrite version of Auraxium. This should be addressed.

Additional things to add to the Wiki:

- ~~[ ] `auraxium.census` Tutorial~~ (Moved to RtD; together with the new API primer everything should be covered)
- [x] Refreshed API primer
- [x] Add list of known API error messages and codes
- [x] Add mapping of metagame event IDs to zone IDs
