### ISSUE TITLE
Add unit tests for object model

### ISSUE THREAD

**Issue by leonhard-s** [leonhard-s/auraxium#24]
With the internal restructuring going on in the `models` branch right now (065a0e9c and following), unit tests for the object model should be added before merging to ensure compatibility.

**Housekeeping:**
- [x] Update the existing test cases to ensure full coverage:
  - [x] `cache_test.py`
  - [x] `census_test.py` 
  - [x] `query_test.py`
- [x] Set up a custom service ID for repository CI/CD as not all things can be tested offline

**Object model tests:**
- [x] Add a separate set of tests for the upcoming `models` submodule. These will be run regularly to ensure the object model matches the API, without having to wait for users to find errors.
- [x] Add event streaming test cases
- [ ] ~~Add proxy system test cases~~
- [x] Add online test cases for common operations. This will require some slow-down to be a good API citizen.

**Bonus points:**
- [x] Add a test coverage checker through GitHub actions
- [x] Add a test coverage status badge

**Comment by leonhard-s** [comment]
Skipped the proxy system test cases as I am not sure if it is a system worth keeping down the road. This will be tracked in an upcoming issue.
